services:
  backend:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    env_file:
      - .env
    environment:
      # Use the docker-compose service hostnames so containers can talk to each other
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/barstar
      REDIS_URL: redis://redis:6379/0
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: ghcr.io/barstar-offical/barstar-postgres-age:16
    container_name: barstar-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - ./_data/pg:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
