name: Test

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and run tests in devcontainer
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            make lint
            make test
